{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tokenizer.fullname" . }}
  labels:
    {{- include "tokenizer.labels" . | nindent 4 }}
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tokenizer.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetAverageHTTPRequest }}
    - type: Pods
      pods:
        metric:
          name: tokenizer_client_connected
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.targetAverageHTTPRequest }}
  {{- end }}
{{- end }}
